@server = http://localhost:8081

### SIGN UP user (creates entry in users collection)
POST {{server}}/user/signup
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "User",
  "username": "testuser",
  "email": "test@test.com",
  "password": "password123"
}

### GET profile AFTER signup
GET {{server}}/api/userProfile/testuser

### UPDATE profile info
PUT {{server}}/api/userProfile/testuser
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "User",
  "email": "test@test.com",
  "bio": "My profile"
}

### GET profile AFTER update
GET {{server}}/api/userProfile/testuser

### GET profile for user that does NOT exist (should return 404)
GET {{server}}/api/userProfile/notARealUser

### UPDATE profile with only one field (bio)
PUT {{server}}/api/userProfile/testuser
Content-Type: application/json

{
  "bio": "Bio"
}

### GET again to confirm bio updated
GET {{server}}/api/userProfile/testuser

### CHANGE PASSWORD using same profile route
PUT {{server}}/api/userProfile/testuser
Content-Type: application/json

{
  "currentPassword": "password123",
  "newPassword": "newpassword123"
}

### LOGIN with NEW password
POST {{server}}/user/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "newpassword123"
}

### DELETE Profile + User
DELETE {{server}}/api/userProfile/account/testuser

### Make Admin
POST {{server}}/user/signup
Content-Type: application/json

{
  "firstName": "THEADMIN",
  "lastName": "THEADMIN",
  "username": "Adminmain",
  "email": "Adminmain@test.com",
  "password": "Adminmain",
  "role": "admin"
}