// Post a new user on geussr leaderboard and hilo leaderboard
@baseUrl = http://localhost:8081/leaderboard/
POST http://localhost:8081/leaderboard/guessr
Content-Type: application/json
{
    "game": "guessr",
    "username": "dummyUser",
    "score": 100
}

###
POST http://localhost:8081/leaderboard/hilo
Content-Type: application/json
{
    "game": "hilo",
    "username": "dummyUser",
    "score": 100
} 