// Update the highscore of the user "dummyUser" on guessr leaderboard
PUT http://localhost:8081/leaderboard/guessr/
Content-Type: application/json
{
    "game": "guessr",
    "username": "dummyUser",
    "score": 150
}

###

PUT http://localhost:8081/leaderboard/hilo/
Content-Type: application/json
{
    "game": "hilo",
    "username": "dummyUser",
    "score": 150
}