@baseUrl = http://localhost:8081/leaderboard

PUT {{baseUrl}}/hilo/dummyUser
Content-Type: application/json
{
    "highscore": 150
}

###

PUT {{baseUrl}}/guessr/dummyUser
Content-Type: application/json
{
    "highscore": 150
}