// Test for HiLo leaderboard POST 
POST http://localhost:8081/leaderboard/HiLo
Content-Type: application/json

{
  "username": "Alice",
  "score": 5
}

###
// Test for Guessr leaderboard POST
POST http://localhost:8081/leaderboard/Guessr
Content-Type: application/json

{
  "username": "Alice",
  "score": 5
}
