
### Add another HiLo score for the same user
POST http://localhost:8081/coolmoviegamez/hilo/johndoe
Content-Type: application/json

{
  "game": "hilo",
  "gamemode": "classic",
  "score": 12
}



###

### Get ALL HiLo scores
GET http://localhost:8081/coolmoviegamez/hilo/